const ResidentFeedbackShared = (() => {
  const qs = (s, r=document) => r.querySelector(s);
  const qsa = (s, r=document) => [...r.querySelectorAll(s)];
  const esc = (v) => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const escAttr = (v) => esc(v).replace(/`/g,'&#96;');
  const cfg = () => ({ ...(window.RESIDENT_FEEDBACK_CONFIG || {}), API_BASE_URL: localStorage.getItem('RF_API_BASE_URL') || (window.RESIDENT_FEEDBACK_CONFIG || {}).API_BASE_URL, PUBLIC_API_KEY: localStorage.getItem('RF_PUBLIC_API_KEY') || (window.RESIDENT_FEEDBACK_CONFIG || {}).PUBLIC_API_KEY });
  function apiReady(){ const c=cfg(); return c.API_BASE_URL && !c.API_BASE_URL.includes('PASTE_') && c.PUBLIC_API_KEY && !c.PUBLIC_API_KEY.includes('PASTE_'); }
  function jsonp(action, params={}){ const c=cfg(); if(!apiReady()) return Promise.reject(new Error('חסרה הגדרת Backend URL או Public API Key')); const cb=`__rf_${Date.now()}_${Math.random().toString(36).slice(2)}`; const url=new URL(c.API_BASE_URL); url.searchParams.set('action',action); url.searchParams.set('publicKey',c.PUBLIC_API_KEY); url.searchParams.set('callback',cb); Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,v??'')); return new Promise((resolve,reject)=>{ const sc=document.createElement('script'); const t=setTimeout(()=>{cleanup();reject(new Error('Timeout מול Apps Script'));},30000); function cleanup(){clearTimeout(t); delete window[cb]; sc.remove();} window[cb]=(res)=>{cleanup(); res && res.ok ? resolve(res.data) : reject(new Error((res&&res.error)||'שגיאה'));}; sc.onerror=()=>{cleanup();reject(new Error('טעינת Apps Script נכשלה'));}; sc.src=url.toString(); document.body.appendChild(sc); }); }
  function post(action, payload={}){ const c=cfg(); if(!apiReady()) return Promise.reject(new Error('חסרה הגדרת Backend URL או Public API Key')); return new Promise((resolve,reject)=>{ const requestId=`req_${Date.now()}_${Math.random().toString(36).slice(2)}`; const form=document.createElement('form'); form.method='POST'; form.action=c.API_BASE_URL; form.target='transportFrame'; form.className='hidden'; const fields={action,publicKey:c.PUBLIC_API_KEY,responseMode:'iframe',requestId,payload:JSON.stringify(payload)}; Object.entries(fields).forEach(([name,value])=>{ const i=document.createElement('input'); i.name=name; i.value=value; form.appendChild(i); }); const timer=setTimeout(()=>{cleanup(); reject(new Error('הפעולה אולי בוצעה, אבל לא התקבלה תשובה מהשרת. רענן ובדוק.'));},120000); function listener(ev){ if(!ev.data || ev.data.type!=='RESIDENT_FEEDBACK_RESPONSE' || ev.data.requestId!==requestId) return; cleanup(); ev.data.ok ? resolve(ev.data.data) : reject(new Error(ev.data.error || 'שגיאת שרת')); } function cleanup(){ clearTimeout(timer); window.removeEventListener('message',listener); form.remove(); } window.addEventListener('message',listener); document.body.appendChild(form); form.submit(); }); }
  function toast(msg){ const t=qs('#toast'); if(!t) return alert(msg); t.textContent=msg; t.classList.remove('hidden'); setTimeout(()=>t.classList.add('hidden'),3500); }
  function showAlert(selector,msg,type='info'){ const el=qs(selector); if(!el) return; el.textContent=msg; el.className=`alert ${type}`; }
  function hideAlert(selector){ const el=qs(selector); if(el) el.classList.add('hidden'); }
  function unique(arr){ return [...new Set((arr||[]).filter(Boolean).map(v=>String(v).trim()))].sort((a,b)=>a.localeCompare(b,'he')); }
  function csv(rows){ return rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n'); }
  function download(name, content, type='text/csv;charset=utf-8'){ const blob=new Blob(['\ufeff'+content],{type}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; a.click(); URL.revokeObjectURL(a.href); }
  function countBy(rows, fn){ return rows.reduce((m,r)=>{ const k=fn(r)||'לא הוגדר'; m[k]=(m[k]||0)+1; return m; },{}); }
  function renderBars(el, counts){ const entries=Object.entries(counts||{}).sort((a,b)=>b[1]-a[1]); const max=Math.max(1,...entries.map(x=>x[1])); el.innerHTML=entries.length?entries.map(([label,n])=>`<div class="bar-row"><span>${esc(label)}</span><div><i style="width:${Math.round(n/max*100)}%"></i></div><b>${n}</b></div>`).join(''):'<p class="muted">אין נתונים</p>'; }
  function table(el, headers, rows){ el.innerHTML=`<thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c??''}</td>`).join('')}</tr>`).join('')}</tbody>`; }
  return {qs,qsa,esc,escAttr,cfg,jsonp,post,toast,showAlert,hideAlert,unique,csv,download,countBy,renderBars,table};
})();
